### ISSUE TITLE
Use https for repository

### ISSUE THREAD

**Issue by benmccann** [gawkermedia/play2-closure#19]
The readme says add resolvers += "pk11" at "http://pk11-scratch.googlecode.com/svn/trunk" to your settings. However, that presents a security risk. Please see http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/ for more info

**Comment by balagez** [comment]
Thanks for reporting this @benmccann. Readme is a bit outdated, you probably don't even need that resolver so I'll soon update it.

**Comment by balagez** [comment]
I removed the incorrect piece of information from the documentation. This library is currently not published anywhere and in order to use it, you need to manually build it. This is now reflected in the readme.
